# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fd7cc0d49f48c84e68fc022378943e28002c9b18d0c3fdebe2ff15f35cd1335902f9b1e3e906239f3e45ed116381125808175c11e728635d61da7f0a7941857

test:
  secret_key_base: 8c70e443dc1d461369759bae4347fc3f814d640faa9bcdf7c8324a434e3b45630271f2772f7add022590e6e80eb345fb6af5ecab3668e1d33ee5110f4d06e41b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
